obj-m += lnbp21.o
KERNSRC="/usr/src/linux/include/media"
EXTRA_CFLAGS += -I${KERNSRC}
KERNELSOURCE="/usr/src/linux/drivers/media"
EXTRA_CFLAGS += -I${KERNELSOURCE}/usb/dvb-usb
EXTRA_CFLAGS += -I${KERNELSOURCE}/dvb-frontends
EXTRA_CFLAGS += -I${KERNELSOURCE}/tuners
EXTRA_CFLAGS += -I${KERNELSOURCE}/dvb-core

